# function to replant
def smart_plant():
    # get the type of plant to plant on the current spot
    plant_type = planting_map[get_world_size() - 1 - get_pos_y()][get_pos_x()]

    # function call to make Grassland or Soil however needed
    smart_till(plant_type)
    # plant type of plant that is wanted here
    plant(entity_translator[plant_type])


# function to till however required
def smart_till(plant_type):
    # make Soil if needed
    if get_ground_type() != Grounds.Soil and till_check[plant_type]:
        till()
    # make Grassland if needed
    elif get_ground_type() != Grounds.Grassland and not till_check[plant_type]:
        till()


# dictionary to get the entity for the shorthand supplied
entity_translator = {
    "grass": Entities.Grass,
    "tree": Entities.Tree,
    "bush": Entities.Bush,
    "carrot": Entities.Carrot,
    "pumpkin": Entities.Pumpkin,
    "cactus": Entities.Cactus,
}


# dictionary to find required Ground type by shorthand plant type
till_check = {
    "grass": False,
    "tree": False,
    "bush": False,
    "carrot": True,
    "pumpkin": True,
    "cactus": True,
}

# map to show what should be planted where
planting_map = [
    [
        "cactus",
        "grass",
        "tree",
        "grass",
        "cactus",
        "cactus",
        "grass",
        "tree",
        "grass",
        "cactus",
    ],
    [
        "grass",
        "tree",
        "grass",
        "cactus",
        "carrot",
        "carrot",
        "cactus",
        "grass",
        "tree",
        "grass",
    ],
    [
        "tree",
        "grass",
        "cactus",
        "grass",
        "carrot",
        "carrot",
        "grass",
        "cactus",
        "grass",
        "tree",
    ],
    [
        "grass",
        "cactus",
        "grass",
        "pumpkin",
        "pumpkin",
        "pumpkin",
        "pumpkin",
        "grass",
        "cactus",
        "grass",
    ],
    [
        "cactus",
        "carrot",
        "carrot",
        "pumpkin",
        "pumpkin",
        "pumpkin",
        "pumpkin",
        "carrot",
        "carrot",
        "cactus",
    ],
    [
        "cactus",
        "carrot",
        "carrot",
        "pumpkin",
        "pumpkin",
        "pumpkin",
        "pumpkin",
        "carrot",
        "carrot",
        "cactus",
    ],
    [
        "grass",
        "cactus",
        "grass",
        "pumpkin",
        "pumpkin",
        "pumpkin",
        "pumpkin",
        "grass",
        "cactus",
        "grass",
    ],
    [
        "tree",
        "grass",
        "cactus",
        "grass",
        "carrot",
        "carrot",
        "grass",
        "cactus",
        "grass",
        "tree",
    ],
    [
        "grass",
        "tree",
        "grass",
        "cactus",
        "carrot",
        "carrot",
        "cactus",
        "grass",
        "tree",
        "grass",
    ],
    [
        "cactus",
        "grass",
        "tree",
        "grass",
        "cactus",
        "cactus",
        "grass",
        "tree",
        "grass",
        "cactus",
    ],
]
planting_map = [
    [
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
    ],
    [
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
    ],
    [
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
    ],
    [
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
    ],
    [
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
    ],
    [
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
    ],
    [
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
    ],
    [
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
    ],
    [
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
    ],
    [
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
        "tree",
        "bush",
    ],
]
